# we create a Docker image from the source code
version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: testdb
    networks:
      - nestjs-network

  # Create another container for "TEST"
  test-database:
    image: postgres:15.0
    container_name: test-database
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
networks:
  nestjs-network:
# How to remove containers/volumes
# ----------------
# docker compose rm dev-database --stop --force --volumes
